#ifndef BEAVER_VERSION_HPP
#define BEAVER_VERSION_HPP
#define BEAVER_VERSION_MAJOR 0
#define BEAVER_VERSION_MINOR 1
#define BEAVER_VERSION_PATCH 0
#define BEAVER_VERSION_STRING "0.1.0"
#endif // BEAVER_VERSION_HPP
